name       : coin
version    : 1.2.0
release    : 1
source     :
    - https://github.com/lainsce/coin/archive/1.2.0.tar.gz : 7a66abe026e55badde4ac5ef1234533b444dd9a4544cd7875524383f3402bbdc
license    : GPL-3.0
component  : office.finance
summary    : Track the virtual currencies in real world currency value. 
description: |
    Track the virtual currencies in real world currency value. 
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - vala
    - meson
setup      : |
    %meson_configure -Dprefix=/usr/bin
build      : |
    %meson_build
install    : |
    %meson_install
