name       : coin
version    : 1.2.6
release    : 8
source     :
    - https://github.com/lainsce/coin/archive/1.2.6.tar.gz : 61ea4e0780f2e4ffcf67b0ebec4c36d3813e0bc9a7bac217d3444a1568f2de26
license    : GPL-3.0-or-later
component  : office.finance
summary    : Track the virtual currencies in real world currency value.
description: |
    Track the virtual currencies in real world currency value.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Update-to-1.2.3.-Make-some-QoL-changes-to-our-shippe.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
