name       : coin
version    : 1.2.2
release    : 3
source     :
    - https://github.com/lainsce/coin/archive/1.2.2.tar.gz : 7b3896711424f335b2f84cdcbc67c487cb0c1e0f78d5f1696c02dd8e76a63172
license    : GPL-3.0-or-later
component  : office.finance
summary    : Track the virtual currencies in real world currency value.
description: |
    Track the virtual currencies in real world currency value.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
