name       : coin
version    : 1.2.5
release    : 5
source     :
    - https://github.com/lainsce/coin/archive/1.2.5.tar.gz : b552e03eeef6245b76edb320c4182e855453170eb0d4041ec95b8feaee66592d
license    : GPL-3.0-or-later
component  : office.finance
summary    : Track the virtual currencies in real world currency value.
description: |
    Track the virtual currencies in real world currency value.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Update-to-1.2.3.-Make-some-QoL-changes-to-our-shippe.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
